name: Clang Tidy Review

# You can be more specific, but it currently only works on pull requests
on: 
  pull_request:
    paths:
      - '*/*.c'
      - '*/*.h'

jobs:
  clang-review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v4

    # Optionally generate compile_commands.json
    - name: Generate compile commands
    - uses: lukka/get-cmake@latest 
      run: |
        make clang-deb
        cmake --build build --target tests
        cmake --build build --target samples

    - name: Review
    - uses: ZedThree/clang-tidy-review@v0.14.0
      id: review
      with:
        split_workflow: true

    - name: Upload artifacts
    - uses: ZedThree/clang-tidy-review/upload@v0.14.0
      id: upload-review

    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
