name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: 
  pull_request:

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    outputs:
      status: ${{ steps.early.conclusion }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # The goal is to force this to pass if it does not need to run.
      - name: Check the diff
        id: early
        run: |
          if $( git diff --name-only HEAD HEAD~1 ) | $( grep -qE '\.(c|h)$' ); then
            exit 0
          else
            exit 1
          fi

  build:
    runs-on: ubuntu-latest
    needs: plan
    if: needs.plan.outputs.status == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get CMake
        uses: lukka/get-cmake@latest 

      - name: Generate Compile Commands
        run: cmake --preset=clang-deb

      - name: Review
        uses: ZedThree/clang-tidy-review@v0.19.0
        id: review
        with:
          split_workflow: true

      - name: Upload artifacts
        uses: ZedThree/clang-tidy-review/upload@v0.19.0
        id: upload-review

      # If there are any comments, fail the check
      - if: steps.review.outputs.total_comments > 0
        run: exit 1
