name: Post Clang Tidy Review Comments

on:
  pull_request:
    workflow_run:
      # The name field of the lint action
      workflows: ["Clang Tidy Review"]
      types:
        - completed

jobs:
  clang-post:
    runs-on: ubuntu-latest

    steps:
      - uses: ZedThree/clang-tidy-review/post@v0.14.0
        # lgtm_comment_body, max_comments, and annotations need to be set on the posting workflow in a split setup
        with:
          # adjust options as necessary
          annotations: false
          max_comments: 10
