name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # The goal is to force this to pass if it does not need to run.
    - name: Check the diff
      run: |
        if git diff --name-only HEAD^ HEAD | grep -qE '\.(c|h)$'; then
          echo "RUN=true" >> $GITHUB_ENV
        else
          echo "RUN=false" >> $GITHUB_ENV
        fi

    - name: Get CMake
      if: ${{ env.RUN }} == 'true'          
      uses: lukka/get-cmake@latest 

    - name: Generate Compile Commands
      if: ${{ env.RUN }} == 'true'          
      run: cmake --preset=clang-deb

    - name: Review
      if: ${{ env.RUN }} == 'true'          
      uses: ZedThree/clang-tidy-review@v0.19.0
      id: review
      with:
        split_workflow: true

    - name: Upload artifacts
      if: ${{ env.RUN }} == 'true'          
      uses: ZedThree/clang-tidy-review/upload@v0.19.0
      id: upload-review

    # If there are any comments, fail the check
    - if: ${{ env.RUN }} == 'true'          
      if: steps.review.outputs.total_comments > 0
      run: exit 1
