name: clang-tidy-post

on:
  workflow_run:
    # The name field of the lint action
    workflows: ["clang-tidy-review"]
    types: [completed, skipped]

jobs:
  check-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # The goal is to force this to pass if it does not need to run.
      - name: Check the diff
        run: |
          if git diff --name-only HEAD HEAD~1 | grep -qE '\.(c|h)$'; then
            echo "run=true" >> $GITHUB_OUTPUT
            echo "will run!"
          else
            echo "run=false" >> $GITHUB_OUTPUT
            echo "will not run!"
          fi

  post:
    runs-on: ubuntu-latest
    needs: check-diff
    if: ${{ needs.check-diff.outputs.run }} == 'true'

    steps:
      - uses: ZedThree/clang-tidy-review/post@v0.19.0
        # lgtm_comment_body, max_comments, and annotations need to be set on the posting workflow in a split setup
        with:
          # adjust options as necessary
          lgtm_comment_body: ''
          annotations: false
          max_comments: 10
