name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check the diff
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qE '\.(c|h)$'; then
          echo "RUN=true" >> $GITHUB_ENV
        else
          echo "RUN=false" >> $GITHUB_ENV
        fi

    - name: Check for early exit.
      if: ${{ env.RUN }} == 'false'          
        run: exit 0

    - name: Get CMake
      uses: lukka/get-cmake@latest 

    - name: Generate Compile Commands
      run: cmake --preset=clang-deb

    - name: Review
      uses: ZedThree/clang-tidy-review@v0.19.0
      id: review
      with:
        split_workflow: true

    - name: Upload artifacts
      uses: ZedThree/clang-tidy-review/upload@v0.19.0
      id: upload-review

    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
