name: clang-tidy-post

on:
  workflow_run:
    # The name field of the lint action
    workflows: ["clang-tidy-review"]
    types:
      - completed

jobs:
  build:
     # avoid trying to post comments on a merged PR
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest

    steps:
      - uses: ZedThree/clang-tidy-review/post@v0.19.0
        # lgtm_comment_body, max_comments, and annotations need to be set on the posting workflow in a split setup
        with:
          # adjust options as necessary
          token: ${{ secrets.GITHUB_TOKEN }}
          lgtm_comment_body: ''
          annotations: false
          max_comments: 10
