
name: Linux Build

on:
  push:
    branches:
      - main
    paths:
      - '*/*.c'
      - '*/*.h'
  pull_request:
    branches:
      - main
    paths:
      - '*/*.c'
      - '*/*.h'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: lukka/get-cmake@latest 

    - name: Delete non-library files
      run: |
        rm -rf samples/
        rm -rf tests/

    - name: Build with Makefile Generator
      run: |
        make gcc-deb
        make install

    - name: Build with Ninja Generator
      run: |
        make clean
        make clang-deb
        make install
