name: linux-build

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-diff:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # The goal is to force this to pass if it does not need to run.
      - name: Check the diff
        run: |
          if git diff --name-only HEAD HEAD~1 | grep -qE '\.(c|h)$|\.cmake|CMakeLists|Config\.cmake\.in'; then
            echo "run=true" >> $GITHUB_OUTPUT
          else
            echo "run=false" >> $GITHUB_OUTPUT
          fi

  build:
    runs-on: ubuntu-latest
    needs: check-diff
    if: ${{ needs.check-diff.outputs.run }} == 'true'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: lukka/get-cmake@latest 

    - name: Delete non-library files
      run: |
        rm -rf samples/
        rm -rf tests/

    - name: Build with Clang and Ninja Generator
      run: |
        make clang-deb
        make install

    - name: Build with GCC and Makefile Generator
      run: |
        make clean
        make gcc-deb
        make install

