name: Linux Build

on:
  push:
    branches:
      - main
    paths:
      - '*/*.c'
      - '*/*.h'
  pull_request:
    branches:
      - main
    paths:
      - '*/*.c'
      - '*/*.h'
  workflow_dispatch:

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: lukka/get-cmake@latest 

    - name: Delete non-library files
      run: |
        rm -rf samples/
        rm -rf tests/

    - name: Build with Clang and Ninja Generator
      run: |
        make clang-deb
        make install

    - name: Build with GCC and Makefile Generator
      run: |
        make clean
        make gcc-deb
        make install

