name: Create Tagged Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    permissions:
        contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clean Repository
        run: |
          git config user.email "agl.alexglopez@gmail.com"
          git config user.name "Alex Lopez"
          git checkout -b release-${GITHUB_REF#refs/tags/}
          git rm -r --cached tests samples images res vcpkg etc || true
          git commit -m "Remove unnecessary files for release ${GITHUB_REF#refs/tags/}"
          git push origin release-${GITHUB_REF#refs/tags/}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release Notes:
          draft: false
          prerelease: false

      - name: Delete Tag Branch
        run: |
          git push --delete origin release-${GITHUB_REF#refs/tags/}
