name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup cl.exe
      uses: ilammy/msvc-dev-cmd@v1

    - name: Delete non-library files
      run: |
        Remove-Item -Path samples -Recurse
        Remove-Item -Path tests -Recurse


    - name: Configure with CMake
      run: cmake -S . -B build -G "NMake Makefiles"

    - name: Build with nmake
      run: |
        cd build
        nmake
